/*
 * File: app/view/DetailContainer.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ToDo.view.DetailContainer', {
    extend: 'Ext.Container',
    alias: 'widget.detailcontainer',

    requires: [
        'Ext.TitleBar',
        'Ext.Button',
        'Ext.form.Panel',
        'Ext.form.FieldSet',
        'Ext.field.Number',
        'Ext.field.DatePicker',
        'Ext.picker.Date'
    ],

    config: {
        itemId: 'mycontainer',
        layout: 'fit',
        items: [
            {
                xtype: 'titlebar',
                docked: 'top',
                items: [
                    {
                        xtype: 'button',
                        id: 'BackButton',
                        ui: 'back',
                        text: '戻る'
                    },
                    {
                        xtype: 'button',
                        align: 'right',
                        id: 'DeleteButton',
                        ui: 'decline',
                        iconCls: 'trash',
                        text: ''
                    }
                ]
            },
            {
                xtype: 'formpanel',
                items: [
                    {
                        xtype: 'fieldset',
                        title: 'タスク',
                        items: [
                            {
                                xtype: 'textfield',
                                label: 'タイトル',
                                name: 'title'
                            },
                            {
                                xtype: 'numberfield',
                                label: '所要時間',
                                name: 'require'
                            },
                            {
                                xtype: 'datepickerfield',
                                label: '期限',
                                name: 'deadline',
                                placeHolder: 'yyyy/mm/dd',
                                dateFormat: 'Y/m/d',
                                picker: {
                                    yearFrom: 2014,
                                    yearTo: 2025
                                }
                            }
                        ]
                    },
                    {
                        xtype: 'button',
                        id: 'SaveButton',
                        margin: '.6em',
                        ui: 'action',
                        text: '保存'
                    }
                ]
            }
        ]
    }

});